kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: sh4d1/drone-kubernetes
    tags: latest
    username: sh4d1
    password: 
      from_secret: DOCKER_PASSWORD
  when:
    branch: 
    - master
